### ISSUE TITLE
Pull not working

### ISSUE THREAD

**Issue by raulillana** [creame/trellis-simple-sync#1]
Howdy!

Pull isn't working for my sites. It's like it's pulling from local, because the gzip contents are there*.

Any tips?

Best!
**R**

**Comment by pacotole** [comment]
Hi!

When you make a pull or push, in your destination environment is saved a gzip backup file with the database before the import.

It's for security if you wan't to revert the pull or push.

In the future I would like to develop the tasks to undo a db pull or push.

**Comment by raulillana** [comment]
Howdy @pacotole !

That's ok, i meant i can see the gzip in remote.
But the DB imported (pulled) is the one from local env.

Could it be a missconfiguration issue?

**Comment by pacotole** [comment]
Hola @raulillana (creo que así nos entenderemos mejor 😉 )

Al hacer pull se descarga e importa la base de datos de producción o staging al entorno local.
`./bin/sync.sh staging example.com db pull`

Si me pegas el comando que ejecutas y las salida de consola tendré más información para ayudarte.

Un saludo

**Comment by raulillana** [comment]
Muy buenas @pacotole (vamos pues). 👍

Entiendo cómo funciona. Puedo ver el dump en remoto y local, y me parece buena idea lo que dices. El tema es que a la hora de importar en local los datos de producción, el site local se queda igual que estaba.

He probado varios comandos, puesto que me interesa importar contenidos en su totalidad, pero ninguno me ha funcionado correctamente.

```
./bin/sync.sh production site.com all pull
./bin/sync.sh production site.com database pull
./bin/sync.sh prod site.com db pull
```

Quise probarlos con los dominios y environment de desarrollo, pero creo que no está pensado para funcionar de esa manera, ¿verdad?

En cuanto al output, cabe decir que he reemplazado algunas rutas y la IP del remote host.

```
TASK [Pull uploads from production] **********************************************************************************************************************************
System info:
  Ansible 2.6.1; Darwin
  Trellis version (per changelog): "Allow customizing Nginx `worker_connections`"
---------------------------------------------------
Warning: Permanently added '{REMOTE_HOST_IP}' (XXXX) to the list of known
hosts.
rsync: mkdir
"/local/trellis/site1.com/web/app/uploads" failed:
No such file or directory (2)
rsync error: error in file IO (code 11) at /BuildRoot/Library/Caches/com.appl
e.xbs/Sources/rsync/rsync-52.200.1/rsync/main.c(545) [receiver=2.6.9]

fatal: [hostname]: FAILED! => {"changed": false, "cmd": "/usr/bin/rsync --delay-updates -F --compress --archive --rsh=/usr/bin/ssh -S none -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null --exclude=.DS_Store --out-format=<<CHANGED>>%i %n%L web@{REMOTE_HOST_IP}:/srv/www/site1.com/current/web/app/uploads/ /local/trellis/site1.com/web/app/uploads/", "rc": 11}
	to retry, use: --limit @/local/trellis/uploads.retry

PLAY RECAP ***********************************************************************************************************************************************************
hostname                  : ok=1    changed=0    unreachable=0    failed=1
```

Y luego suelta otro error más.

```
TASK [PULL > Search for https://site1.com and replace with https://site1.test on development] **************************************************************
System info:
  Ansible 2.6.1; Darwin
  Trellis version (per changelog): "Allow customizing Nginx `worker_connections`"
---------------------------------------------------
non-zero return code
Error: The site you have requested is not installed.
Your table prefix is 'xx_'. Found install with table prefix: wp_.
Or, run `wp core install` to create database tables.
fatal: [hostname]: FAILED! => {"changed": true, "cmd": "vagrant ssh -- \"cd /srv/www/site1.com/current && wp search-replace 'https://site1.com' 'https://site1.test' --all-tables\"", "delta": "0:00:03.378925", "end": "2018-11-21 23:36:15.562329", "rc": 1, "start": "2018-11-21 23:36:12.183404", "stderr_lines": ["Error: The site you have requested is not installed.", "Your table prefix is 'xx_'. Found install with table prefix: wp_.", "Or, run `wp core install` to create database tables."], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/local/trellis/database.retry

PLAY RECAP ***********************************************************************************************************************************************************
hostname                  : ok=8    changed=7    unreachable=0    failed=1
```

Cabe decir que estoy usando una arquitectura de varios sites sobre un mismo trellis en un mismo servidor, y he cambiado la configuración del hosts desde la última vez, para hacer funcionar los deploys correctamente por fin. 😅

Tiene bastante pinta de ser algún tema de _missconfiguration_ por algún lado, pero he definido el db_prefix en los env de los wordpress_sites.yml de prod y dev.

Lo vamos viendo. Muchas gracias. 😃

**Comment by raulillana** [comment]
¡Hola!

Parece que actualizando rsync he conseguido avanzar un poco, pero tengo que lidiar con otras movidas relacionadas, como el downgrade de Ansible.

Me preguntaba si el hecho de estar trabajando con subtrees en ésta arquitectura puede tener algo que ver con tanto problemilla.

Un saludo @pacotole.

**Comment by raulillana** [comment]
¡Hola @pacotole!

Feliz año con algo de demora. :)

He tenido que modificar los 2 .yml, para cambiar la ruta de los Bedrocks, añadiendo un acceso al directorio por encima de Trellis:

`src: "../{{ project_local_path }}/web/app/uploads/"` @ upload.yml#L28
`src: "../{{ project_local_path }}/{{ sync_file }}"` @ database.yml#L82

Con esto ya funciona todo perfecto. Gracias por la paciencia. Un abrazo.

**Comment by pacotole** [comment]
Me alegro mucho de que encontraras la solución :smiley: 
Me pilló una temporada que no daba abasto para entrar por aquí.

Un saludo
