### ISSUE TITLE
'dict object' has no attribute 'example.com'

### ISSUE THREAD

**Issue by foveann** [creame/trellis-simple-sync#2]
Thank you for creating this script, I've been searching for something like this for a while now.

I followed the instructions for installation but receive the following error message when I try to run "./bin/sync.sh staging example.com db push":
______________________________________________________________
The task includes an option with an undefined variable. The error was: 'dict
object' has no attribute 'example.com'

The error appears to have been in'../trellis/database.yml': line 80, column 9, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:
      - name: PUSH > Push dump file from development to "{{ env }}"
        ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

fatal: [dev.example.com]: FAILED! => {}
______________________________________________________________________

I am running:
Ansible 2.7.10;
Trellis 1.0.3

**Comment by pacotole** [comment]
Hi @foveann 

Please, check in your group_vars/staging/ if `wordpress_sites` and `vault_wordpress_sites` have the same key 'example.com'

**Comment by foveann** [comment]
Yes they are the same.

I'm running the command  "./bin/sync.sh staging example.com db push" from the trellis directory on my local environment. Is that correct?

**Comment by pacotole** [comment]
Yes, it's correct: `./bin/sync.sh staging <your_site_name> db push`

Sorry, but I think the problem is a misconfiguration in your group_vars. Can you deploy on staging successfully?

Also you can paste here the output of "./bin/sync.sh staging example.com db push" script

**Comment by foveann** [comment]
Should I be running  " ./bin/sync.sh staging dev.example.com db push " instead?
dev.example.com = staging
example.com = production

Here is the output of  "./bin/sync.sh staging example.com db push":

PLAY [Sync example.com DATABASE between development <-> staging environments] **************************************************************************************
 [WARNING]: You Ansible version is 2.7.10 but this version of Trellis has only been tested for compatability with Ansible 2.4.0.0 -> 2.7.5. It is advisable to
check for Trellis updates or downgrade your Ansible version.


TASK [Gathering Facts] ********************************************************************************************************************************************
ok: [dev.example.com]

TASK [Abort if environment variable is equal to development] ******************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Export staging database] *****************************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Pull dump file from staging to development] **********************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Delete dump file from staging] ***********************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Backup development database] *************************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Reset development database] **************************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Import database dump on development] *****************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Delete dump file from development] *******************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Search for {{ url_env }} and replace with {{ url_dev }} on development] ******************************************************************************
skipping: [dev.example.com]

TASK [PULL > Search for //{{ domain_env }} and replace with //{{ domain_dev }} on development] ********************************************************************
skipping: [dev.example.com]

TASK [PULL > Cache flush on development] **************************************************************************************************************************
skipping: [dev.example.com]

TASK [PUSH > Export development database] *************************************************************************************************************************
changed: [dev.example.com]

TASK [PUSH > Push dump file from development to staging] **********************************************************************************************************
System info:
  Ansible 2.7.10; Linux
  Trellis 1.0.3: April 30th, 2019
---------------------------------------------------
The task includes an option with an undefined variable. The error was: 'dict
object' has no attribute 'example.com'

The error appears to have been in
'..../trellis/database.yml': line 80, column 9, but
may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


      - name: PUSH > Push dump file from development to "{{ env }}"
        ^ here
We could be wrong, but this one looks like it might be an issue with
missing quotes.  Always quote template expression brackets when they
start a value. For instance:

    with_items:
      - {{ foo }}

Should be written as:

    with_items:
      - "{{ foo }}"

fatal: [dev.example.com]: FAILED! => {}

**Comment by pacotole** [comment]
The problem is that you have different site keys between environments. They must be the same in all environments (development, staging and production).

The site key is (on staging) [here](https://github.com/roots/trellis/blob/master/group_vars/staging/wordpress_sites.yml#L6) and [here](https://github.com/roots/trellis/blob/master/group_vars/staging/vault.yml#L13)

And then the server domain is defined in site_hosts

**Comment by foveann** [comment]
Thank you. Beforehand the sitekey in those files were dev.example.com. If I change the site key in those locations from dev.example.com to example.com, then the script runs without any complaints. The result is that my development db is pushed and synced to my production, not my staging. So I end up with both development and production with synced db and a fresh WP install that remains unaltered on my staging. Sorry about all this back and forth, I really appreciate your help and time.

**Comment by foveann** [comment]
If I change the sitekey to match between development and staging environments to be dev.example.com and run the script : "./bin/sync.sh staging dev.example.com db push" 

I get a different error message that says there is no directory /srv/www/dev.example.com/current even though it does exist. Here is the output:
________________________________________________________________________
PLAY [Sync dev.example.com DATABASE between development <-> staging environments] **********************************************************************************
 [WARNING]: You Ansible version is 2.7.10 but this version of Trellis has only been tested for compatability with Ansible 2.4.0.0 -> 2.7.5. It is advisable to
check for Trellis updates or downgrade your Ansible version.


TASK [Gathering Facts] ********************************************************************************************************************************************
ok: [dev.example.com]

TASK [Abort if environment variable is equal to development] ******************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Export staging database] *****************************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Pull dump file from staging to development] **********************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Delete dump file from staging] ***********************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Backup development database] *************************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Reset development database] **************************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Import database dump on development] *****************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Delete dump file from development] *******************************************************************************************************************
skipping: [dev.example.com]

TASK [PULL > Search for https://dev.example.com and replace with http://example.test on development] ***************************************************************
skipping: [dev.example.com]

TASK [PULL > Search for //dev.example.com and replace with //example.test on development] **************************************************************************
skipping: [dev.example.com]

TASK [PULL > Cache flush on development] **************************************************************************************************************************
skipping: [dev.example.com]

TASK [PUSH > Export development database] *************************************************************************************************************************
System info:
  Ansible 2.7.10; 
  Trellis 1.0.3: April 30th, 2019
---------------------------------------------------
non-zero return code
bash: line 0: cd: /srv/www/dev.example.com/current: No such file or directory
fatal: [dev.example.com]: FAILED! => {"changed": true, "cmd": "vagrant ssh -- 'cd /srv/www/dev.example.com/current && wp db export - | gzip > dev_example_com_db_sync.sql.gz'", "delta": "0:00:06.198835", "end": "2019-05-23 16:41:39.424595", "rc": 1, "start": "2019-05-23 16:41:33.225760", "stderr_lines": ["bash: line 0: cd: /srv/www/dev.example.com/current: No such file or directory"], "stdout": "", "stdout_lines": []}

**Comment by pacotole** [comment]
First, check config if domains are correct for each environment in group_vars and hosts.

Review your config in group_vars:
```
# development
wordpress_sites:
  example.com: # same key on all envs and in vault files
    site_hosts:
      - canonical: example.test # your url domain for local dev
        redirects:
          - www.example.test

# staging
wordpress_sites:
  example.com:
    site_hosts:
      - canonical: dev.example.com # your url domain for staging

# production
wordpress_sites:
  example.com:
    site_hosts:
      - canonical: example.com # your url domain for production
        redirects:
          - www.example.com
```

Review your config in hosts:
```
# development (don't change)

# staging
[staging]
dev.example.com # your url domain for staging

[web]
dev.example.com # your url domain for staging

# production
[production]
example.com # your url domain for production

[web]
example.com # your url domain for production
```

Second, if you have changed the site key in staging from `dev.example.com` to `example.com` you must provision and deploy server again because the paths have changed 

> "bash: line 0: cd: /srv/www/dev.example.com/current: No such file or directory"

**Comment by foveann** [comment]
Perhaps this is a multi-site issue or I have set up my site incorrectly. In my original setup, my /srv/www/ folder has two folders 1) dev.example.com and 2) example.com. 

I followed your instructions and got a complaint for deploying staging environment. If it is related to a multi-site setting, I am not familiar enough with the code to know what changes to make. Here is the error message:

TASK [deploy : WordPress Installed?] *******************************************
System info:
  Ansible 2.7.10; 
  Trellis 1.0.3: April 30th, 2019
---------------------------------------------------
non-zero return code
Error: Error establishing a database connection. This either means that the
username and password information in your `wp-config.php` file is incorrect
or we can’t contact the database server at `localhost`. This could mean your
host’s database server is down.
fatal: [dev.example.com]: FAILED! => {"changed": false, "cmd": ["wp", "core", "is-installed", "--skip-plugins", "--skip-themes", "--require=/srv/www/example.com/shared/tmp_multisite_constants.php"], "delta": "0:00:00.199847", "end": "2019-05-24 11:24:55.990072", "failed_when_result": true, "rc": 1, "start": "2019-05-24 11:24:55.790225", "stderr_lines": ["Error: Error establishing a database connection. This either means that the username and password information in your `wp-config.php` file is incorrect or we can’t contact the database server at `localhost`. This could mean your host’s database server is down."], "stdout": "", "stdout_lines": []}

**Comment by foveann** [comment]
I just created another website and managed to set it up properly. Your script works perfectly. Thanks!

**Comment by pacotole** [comment]
A good news, I'm glad
